conda-forge/gdal-feedstock

- recipe/meta.yaml
I thought it would be OK to leave Win+PY35 failing, as a reminder that we should try again in a near future, but this is giving me some headaches in the IOOS channel.
> Skip Win+PY35 and add kmuehlbauer

- recipe/bld.bat
- recipe/meta.yaml
- recipe/run_test.py
This pull request enables building GDAL with VC 2015 for Python 3.5. It also adds openjpeg and curl libraries, plus revamps the run_tests.py script.
I have fixed hdf5 to the 1.15.1 version until the problems with netcdf are resolved.
> Allow Python35 builds on Windows

- .travis.yml
- appveyor.yml
- recipe/build.sh
- recipe/meta.yaml
I had problems compiling `libxml2` with `libzma` support, but after removing `libzma` from `libxml2` both `gdal` and `fiona` had issues with missing `libzma`. Let's try this approach for now, but I suspect my original problem was because `homebrew` was not properly removed (my bad [here](https://github.com/conda-forge/conda-smithy/pull/114/files#diff-4db594a93663b6584405af3d0607f2b6R30)). So I will re-visit this at a later time and maybe re-add `libzma` on `libxml2`. For now this seems to work and we need to get `gdal` and `fiona` out there.
> Re-render and add libzma

- recipe/meta.yaml
- recipe/scripts/activate.sh
See the related issue and PR at https://github.com/conda/conda-recipes/issues/677 and https://github.com/conda/conda-recipes/pull/679
I've tested this locally in bash and zsh.
> Make gdal activate script also work in other shells.

- recipe/build.sh
- recipe/meta.yaml
This PR updates the GDAL build to use the toolchain which should fix linking errors on OSX.
ping @jakirkham
> use toolchain

- .travis.yml
- recipe/build.sh
- recipe/meta.yaml
I forgot to unpin `conda-build` when using `toolchain` which means symlinks get left in. This should fix it.
cc @jakirkham
> remove symlinks

- recipe/meta.yaml
Updated `meta.yaml` to version 2.1.2 which was released (ahem...) recently. Solves a pretty large number of bugs. I also put the build number down to 0, but I haven't changed anything else...
> Bumped version to 2.1.2 build0

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.py
I seem to have encountered the issue described in https://github.com/swig/swig/issues/567.
in python 3.5
``` python
from osgeo import ogr
def make_geom():
geom = ogr.Geometry(ogr.wkbPoint)
geom.AddPoint_2D(0, 0)
return geom
def gen_list(N):
for i in range(N):
geom = make_geom()
yield i
N = 10
print('gen', list(gen_list(N)))
```
produces `SystemError: <built-in function delete_Geometry> returned a result with an error set`
The issue have been resolved in swig 3.0.8 but the bindings that come with GDAL sources are generated with SWIG 2.0.12.
Regenerating the bindings with the latest swig resolves the issue, but also adds libpcre as a run-time dependency.
> Regenerate python bindings

- recipe/meta.yaml
I've updated meta.yaml in the 1.x branch to account for the proj4 rename.
> Rename proj4 in gdal_1.x branch

- recipe/bld.bat
- recipe/meta.yaml
I use conda in Windows with the Bash shell,  so need environment variable activation 
shell scripts as well as batch scripts. I'm sure I'm not the only one.
> Support Windows Bash users

- appveyor.yml
- recipe/meta.yaml
- recipe/scripts/deactivate.bat
Currently, on deactivating an environment, this script outputs each step its executing. Hide these executions.
> hide batch command output

- recipe/meta.yaml
- recipe/scripts/activate.sh
Unfortunately Windows installs of GDAL place the data files in a different directory to Linux installed.
This patch checks before setting environment variables to see if the target directory exists.
It should fix GDAL environment variables for Windows bash users.
> Update gdal-activate.sh to work in Windows + Linux

- ci_support/run_docker_build.sh
- recipe/meta.yaml
Python 3.6 Linux builds are in https://github.com/conda-forge/gdal-feedstock/tree/gdal2_PY36_linux now.
> Build all but Linux+PY36

- recipe/meta.yaml
Should with the packages that still rely on the old `proj4 <6`, like `cartopy` and `rasterio`, but got hit by the `cfitsio` ABI breakage.
> rebuild without cfitsio

- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015vc14.yaml
- recipe/meta.yaml
I made a mistake with build number `3`. This should fix it for the old `icu` version.
> Bump build number

- recipe/build.sh
- recipe/meta.yaml
- recipe/userfaultfd.h
Checklist
Fixes #323 
1. Solution was to drop the userfaultfd.h header for compilation and then remove it. 
2. Had to define "__NR_userfaultfd" variable in the headerfile as this does not appear to be defined in the x86_64 environment on centos 6. Can possibly move that to a patch to cpl_userfaultfd.h.
> Build with userfaultfd support

- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.bat
- recipe/run_test.sh
This removes the static libraries from the main package according to [CFEP-18](https://github.com/conda-forge/cfep/pull/34). This might break some downstream builds but this is intended and we should fix the downstream builds to use the shared libraries before adding an output here.
Checklist
> CFEP-18: Remove static libraries from main build

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- conda-forge.yml
Checklist
closes #532
closes #528
closes #526
closes #487
closes #491
> Drop v3.1.x and v3.2.x from abi_migration_branches

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- conda-forge.yml
- recipe/meta.yaml
Checklist
~~I have no idea if I done this right, but the rerender seems to have done what I thought was needed?  I throw myself at the benevolence of the conda-forge experts to kindly educate me if this is the wrong approach...~~
PR morphed into cross compiling aarch and ppc on linux 64 to gain ~5-6x speedup.
> Cross compile linux aarch and ppc on linux 64

- conda-forge.yml
Given the build failure with newer `poppler` in #599, perhaps it is time to let go of the `3.3.x` bot migration branch.
> [ci skip] [skip ci] [cf admin skip] ***NO_CI*** drop 3.3 migration branch

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
Checklist
This PR brings GDAL back in line with conda-forge-pinning, which just corrected the geotiff pin to 1.7.0.  The issue is that some repos were getting 1.7.1 due to the loose pinning and then creating dependency islands.
> Rebuild for geotiff 1.7.0

- recipe/run_test.sh
I'm unclear why the recipe tests this particular driver... Anyway I'm
about to either remove that driver upstream (cf
https://github.com/OSGeo/gdal/issues/5173), or perhaps less radical
option, just require to have a DODS_RASTER: prefix at the beginning of the
connection string. In any case, if not changing this recipee, this would
break the GDAL upstream CI task that uses this recipee to build a Conda package from master.
(I don't think this justify bumping the version number?)
> run_test.sh: remove DODS testing

- conda-forge.yml
Checklist
*  Bumped the build number (if the version is unchanged)
Since the 3.6 build with cmake is a rather dramatic change and the dependency graph for gdal is very large, is there appetite to keep around a `v3.5.x` bot abi migration branch?
> create v3.5.x bot migration branch [ci skip] ***NO_CI***

- recipe/meta.yaml
libdap4 was necessary for the DODS drivers, but they have been removed in GDAL 3.5.0, so just drop this dependency.
pcre is deprecated. GDAL supports pcre2 too, so use the later
Checklist
> Remove unused libdap4 dependency, and update pcre->pcre2

- recipe/meta.yaml
- recipe/scripts/activate.bat
- recipe/scripts/activate.ps1
I realized that the failure in the testing of the Arrow/Parquet plugins on Windows in https://github.com/conda-forge/gdal-feedstock/pull/679 was due to a wrong GDAL_DRIVER_PATH in activate.bat and activate.ps1
This PR fixes that independently
> activate.bat and activate.ps1: fix GDAL_DRIVER_PATH

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
It is a faster alternative for zlib in a number of situations, which can accelerate zlib compression/decompression by about a factor of 2.
Checklist
> Add libdeflate dependency

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
This reverts commit https://github.com/conda-forge/gdal-feedstock/commit/b3bd22d6d45e788b1206a868a88d820c0f6224d5 because of an issue when using gdal and scipy.spatial.Delaunay, the later apparently bundling qhull.
See https://github.com/conda-forge/qgis-feedstock/issues/284#issuecomment-1356490896 for details
Checklist
> meta.yaml: use bundled qhull instead of packaged one 

- recipe/install_python.bat
- recipe/install_python.sh
- recipe/meta.yaml
This is cleaner than manual copying of the pre-generated files, especially since in GDAL master/3.7.0dev, those files have been removed from git, and thus GDAL CI Conda-based master builds are currently broken
> install_python.sh/bat: use python_generated_files target

- recipe/0001-cpl_zipOpenNewFileInZip3-validate-length-of-filename.patch
- recipe/meta.yaml
Cherry-picking of upstream commit
https://github.com/OSGeo/gdal/commit/725070cc38cd47d870bc1ed394b9275013aab79e
(will have to be dropped for 3.8.0)
Checklist
> Add patch to fix validation issues in cpl_zipOpenNewFileInZip3() (CVE-2023-45853)

- recipe/0001-Fix-build-error-with-libxml2-2.12.patch
- recipe/0002-Fix-build-error-with-libxml2-2.12-cont-d.patch
- recipe/meta.yaml
Anticipate a future transition to libxml 2.12. Upstream patch in https://github.com/OSGeo/gdal/commit/cbed9fc91dffba30d0f9a6a06a412a04d9cd36fa and https://github.com/OSGeo/gdal/commit/ec33f6d6dfe944f59dc5454d01b4d000d9479c02
Checklist
> Add upstream patch for compatibility with libxml2 2.12

- recipe/0002-Fix-build-error-with-libxml2-2.12.patch
- recipe/0003-Fix-build-error-with-libxml2-2.12-cont-d.patch
- recipe/meta.yaml
> [v3.7.x backport]Add upstream patch for compatibility with libxml2 2.12

- recipe/meta.yaml
- recipe/test_script_exist.bat
Checklist
Closes #834 
Now that GDAL 3.9 has landed, we can test the proper entry points (Python apps, called without the .py extension). Also incorporated are changes (as a result of upstream GDAL fixes) so that all of these apps are now tested with `--help`, see https://github.com/OSGeo/gdal/issues/8717.
There has been a bit of churn on GDAL upstream regarding these entry points, see:
- https://github.com/OSGeo/gdal/pull/8718
- https://github.com/OSGeo/gdal/pull/8774
- https://github.com/OSGeo/gdal/issues/8811
- https://github.com/OSGeo/gdal/pull/8815
- https://github.com/OSGeo/gdal/pull/8824
The commands including `.py` are still the ones shown in GDAL docs, so for now I test both e.g. `gdal_calc.py` and `gdal_calc`.
> Test entry points, call all Python apps with --help

- recipe/install_python.sh
This patch (which is an upstreaming of a OSGeo/GDAL one: https://github.com/OSGeo/gdal/commit/c9c4e09c457a9407873ff4d947a131ea4d1bc9b5) doesn't seem necessary for builds using conda-forge infrastructure, but I found it necessary for GDAL master builds running on GDAL GitHub action CI, where for some reason, for some Python configuration (namely python 3.12.5 + numpy 2.0), the FindPython CMake package doesn't manage to locate numpy (but it works for other python versions using numpy 2.0)...
I'd note that the install_python.bat already uses a similar trick, so at least that's not a totally new thing.
I didn't bump the build number, as this should not require updating exiting packages.
> install_python.sh: manually set Python_NumPy_INCLUDE_DIR

- conda-forge.yml
The `v3.8.x` branch has become un-buildable with current conda-forge pinning, so any rerender will lead to a busted build.
see #982 for tiledb
see #980 for python 3.13
see #974 for poppler 24.08
We can always add back a v3.9.x migration branch, when that time comes :)
> [ci skip] [skip ci] [cf admin skip] ***NO_CI*** drop v3.8.x migration branch

- recipe/0001-Python-bindings-fix-compatibility-issue-with-SWIG-43.patch
- recipe/meta.yaml
Fixes https://github.com/conda-forge/gdal-feedstock/issues/995
Upstream fix in https://github.com/OSGeo/gdal/pull/11154
Checklist
> Python bindings: fix compatibility issue with SWIG 4.3.0 and PYTHONWARNINGS=error

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libarrow180.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/0002-libarrow-18-min-compat.patch
- recipe/meta.yaml
Continuation of https://github.com/conda-forge/gdal-feedstock/pull/997 including a patch needed for GDAL 3.9.3 to be compatible of Parquet files with 0 row groups.
Checklist
> Rebuild for libarrow 18.0 + patch needed for 3.9.3

- recipe/meta.yaml
> meta.yml: pin libgdal-xxxx plugins to same x.y.z version of libgdal-core

- recipe/meta.yaml
- recipe/scripts/activate.sh
> activate.sh: enable bash completion

- recipe/meta.yaml
- recipe/swig-4.3.1-compat.patch
Fixes issue  https://github.com/conda-forge/gdal-feedstock/issues/995 that was fixed for SWIG 4.3.0 but needs a slight adjustment for 4.3.1
Corresponds to GDAL upstream fix:
https://github.com/OSGeo/gdal/commit/19671ee60c3e58242b7a2754744f1b73d3fe6ef7
This patch will have to be dropped for GDAL 3.11
Checklist
> Bring compatibility for SWIG 4.3.1

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/LICENSE_libgeotiff.txt
- recipe/LICENSE_libtiff.txt
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.sh
For the former we have to use internal libtiff and geotiff. I'm not totally sure if it is OK w.r.t conda-forge packaging policies ? Technicially it is safe, since the symbols of those vendored libraries are prefixed with GDAL_ to avoid any clash if  an application/library linking against GDAL is also linked against libtiff
Fixes #752
Checklist
> Add JPEGXL-in-TIFF support and JPEGXL driver
