- recipe/meta.yaml
I should not be sending PRs at 4:47 am.
> fix pre selector

- appveyor.yml
Forgot to update the build matrix in #18
> Update AppVeyor build matrix

- .travis.yml
- appveyor.yml
- ci_support/run_docker_build.sh
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
Ping @gillins I added you as a maintainer here too.
PS: @kmuehlbauer and @gillins I am planning to put `gdal2` into master and start a `gdal 1.x series` branch as soon as the new `fiona` (that will work with `gdal` 2) is released.
> WIP: Back-port PR #17

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.py
This adds support for Python 3.5 on Windows. (I also added `libxml2` and `libspatialite` on OS X.)
> Back-port PR #29

- .travis.yml
- appveyor.yml
- ci_support/run_docker_build.sh
Sorry, I meant to do this as part of #29 . Should explain why no Python 35 versions of GDAL got built.
> ran conda-smithy regenerate

- recipe/meta.yaml
> Pin GDAL 2.0 to jpeg 8*

- .travis.yml
- recipe/meta.yaml
Forgot to do this in #43. (I guess it is time to call it a day and :zzz:)
> Bump build number

- .travis.yml
- appveyor.yml
- recipe/meta.yaml
Should fix https://github.com/conda-forge/wradlib-feedstock/issues/8
Ping @kmuehlbauer
> Pin libpng

- recipe/meta.yaml
- recipe/scripts/activate.sh
Same as #63 for `gdal_1.x` branch.
> Backport #63

- recipe/meta.yaml
- recipe/windowshdf5.patch
Needs https://github.com/conda-forge/libnetcdf-feedstock/pull/1.
Note to self: if this works port it to `gdal 2`.
> Pin to libnetcdf 4.4

- recipe/build.sh
- recipe/meta.yaml
- recipe/windowshdf5.patch
@jgomezdans can you review this to see if everything from your PR is here?
@gillins can you review and merge after @jgomezdans gives the :+1: ?
---
Edit: This PR supersedes #67
> Pin libnetcdf

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
@gillins I am not sure we want all these changes here. Let's iterate this a little bit to fine tune it.
> Port some changes from gdal 1.x into 2.x

- .travis.yml
- appveyor.yml
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.py
Jus testing... Nothing to see here. Move along!
> No toolchain solution

- recipe/build.sh
- recipe/meta.yaml
Testing latest version.
PS: Maybe we should do `1.11.5` too...
> Bump to 2.1.1

- recipe/build.sh
- recipe/meta.yaml
> Add libdap

- recipe/bld.bat
- recipe/build.sh
- recipe/disable_jpeg12.patch
- recipe/meta.yaml
- recipe/run_test.py
- update to latest version of `gdal 1.x` series.
- add `libdap` support
- synced with master changes and updates
> Update to 1.11.5

- recipe/meta.yaml
Hopefully the build number bump will fix https://travis-ci.org/conda-forge/rasterio-feedstock/jobs/170475384#L937
> libdap test

- README.md
- appveyor.yml
- recipe/meta.yaml
`Shapely` and `libspatialite` are already in. Let's try `gdal` now!
> Test geos 351

- .gitattributes
- .travis.yml
- README.md
- appveyor.yml
- ci_support/run_docker_build.sh
- recipe/meta.yaml
- recipe/run_test.py
Not a fix yet... just a test to check if it fails everywhere.
See #131
> Fixes #131

- .travis.yml
- appveyor.yml
- ci_support/run_docker_build.sh
- recipe/bld.bat
- recipe/meta.yaml
CircleCI and Travis-CI may fail due to the extra matrix item. Maybe we will need to branch this.
> rerender with auto

- recipe/meta.yaml
See https://trac.osgeo.org/gdal/wiki/Release/2.1.3-News
> Update to 2.1.3

- .travis.yml
- LICENSE
- recipe/meta.yaml
> Rebuild for icu 58.*

- recipe/meta.yaml
Porting #157 and #160 to the `gdal2_PY36_linux` branch.
> pin hdf5 and geos

- recipe/meta.yaml
Waiting for https://github.com/conda-forge/libgdal-feedstock/pull/2
> Update to 2.2.1

- README.md
- recipe/meta.yaml
See http://trac.osgeo.org/gdal/wiki/Release/2.2.2-News
> update to 2.2.2

- recipe/meta.yaml
See https://github.com/conda-forge/conda-forge.github.io/pull/493
> pin xerces

- appveyor.yml
- recipe/run_test.py
https://github.com/conda-forge/libgdal-feedstock/pull/33/commits/04bad915a98d3d3c8dbea49bb0e1ceae0630deae should fix this once merge.
> Test issue https://github.com/conda-forge/libgdal-feedstock/issues/32

- recipe/meta.yaml
See https://trac.osgeo.org/gdal/wiki/Release/2.2.4-News
> update to 2.2.4

- recipe/meta.yaml
> add pkg-config

- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- recipe/meta.yaml
Same as #270 but without the strict part.
> Re render2

- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- recipe/meta.yaml
This should pin to the latest `giflib 5.1.7`.
> Re render3

- .github/CODEOWNERS
- recipe/meta.yaml
Checklist
I hope this is correct. Was not sure if the bot would automatically add PR for older versions of gdal
> Update recipe for v2.4.2

- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015vc14.yaml
- recipe/meta.yaml
> Rerender master

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .azure-pipelines/build_steps.sh
- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015vc14.yaml
- recipe/meta.yaml
> Rerender 2.4

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .azure-pipelines/run_docker_build.sh
- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015vc14.yaml
- .gitattributes
- README.md
- recipe/meta.yaml
Proj4 was renamed to the new upstream name "proj."
> Rename proj dep

- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015vc14.yaml
- .gitattributes
- README.md
- recipe/meta.yaml
> Rerender for proj 6.2.1

- .ci_support/linux_.yaml
- .ci_support/osx_.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015vc14.yaml
- .gitattributes
- recipe/meta.yaml
> Re render for latest proj

- recipe/meta.yaml
> Make sure tests work outside of the docker image

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_.yaml
- .ci_support/migrations/icu67.yaml
- .ci_support/osx_.yaml
- .ci_support/win_.yaml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
> Rebuild for icu 67

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/migrations/icu67.yaml
- .ci_support/migrations/proj-7.1.0.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- azure-pipelines.yml
- recipe/meta.yaml
add xylar as a maintainer
Checklist
> Update build number, temporarily remove icu migrator

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/migrations/proj711.yaml
- .ci_support/migrations/python39.yaml
- .ci_support/migrations/tiledb21.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- build-locally.py
- recipe/meta.yaml
> Rebuild python39 0 2 h58c898

- recipe/meta.yaml
- recipe/run_test.py
- recipe/set_bld_opts.bat
> add libkml support on Windows

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- build-locally.py
- recipe/meta.yaml
Checklist
*  Bumped the build number (if the version is unchanged)
Lets try this once without a rerender and see if it still fails.
closes #545
> updated v3.3.3

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/geos3100.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
Checklist
Also adds me as a maintainer :)  
closes #550
> Rebuild with GEOS 3.10.0

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/cfitsio400.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for cfitsio400

- conda-forge.yml
This way we won't have to manually update that branch.
Checklist
> [skip ci] Add v3.3.x branch to abi_migration_branches

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/proj820.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Checklist
This rebuilds with proj 8.2.0 on the 3.3.x branch of GDAL.
closes #565
> rebuild with proj 8.2.0 (3.3 branch)

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- conda-forge.yml
- recipe/meta.yaml
Checklist
3.3 branch version of #566
> Cross compile aarch and ppc on linux 64 (3.3 branch)

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/migrations/icu69.yaml
- .ci_support/migrations/openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- README.md
- recipe/meta.yaml
Checklist
This reverts the changes from the #590 intermediate build in support of my never-ending quest on #585.
> Rebuild with icu69 openssl3 libpq

- README.md
- recipe/meta.yaml
Rerendering to catch up to geotiff windows again. See #616
> Rerender for geotiff

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
- recipe/run_test.py
- recipe/test_data/test.zarr/.zgroup
- recipe/test_data/test.zarr/data/.zarray
Checklist
Just put a static copy of the test data in the recipe (alongside the rest) and use that. This removes a Python library from the dependency tree (where there are almost none already) in order to reduce the set of packages GDAL needs to wait on.
> Remove zarr

- recipe/meta.yaml
- recipe/scripts/activate.bat
- recipe/scripts/activate.ps1
Checklist
backports #683 to `v3.5.x` branch
> activate.bat and activate.ps1: fix GDAL_DRIVER_PATH

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
> Improve deps

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
Checklist
Addresses #690 for v3.5.x branch.
@conda-forge-admin, please rerender
> update deps per #690

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/migrations/pcre21040.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
Checklist
Followup manual migration of pcre2 10.40
@conda-forge-admin, please rerender
> rebuild with pcre2 10.40

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/migrations/proj911.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
> Rebuild v3.6.2 with proj 9.1.0

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/migrations/libdeflate117.yaml
- .ci_support/migrations/proj911.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
> Switch back to proj 9.1.1

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- conda-forge.yml
- recipe/install_python.sh
- recipe/meta.yaml
Checklist
*  Bumped the build number (if the version is unchanged)
I'll create the 3.6 branch prior to merging this, or somebody else can beat me to it :)
> GDAL 3.7.0

- .ci_support/migrations/cfitsio420.yaml
- .ci_support/migrations/icu72.yaml
- .ci_support/migrations/libnetcdf491.yaml
- .ci_support/migrations/libnetcdf492.yaml
- recipe/meta.yaml
- recipe/scripts/activate.sh
- recipe/scripts/deactivate.sh
Similar to https://github.com/conda-forge/geotiff-feedstock/pull/57, described in more detail at https://github.com/conda-forge/geotiff-feedstock/issues/56.
Checklist
> POSIX Compliant de/activate scripts

- recipe/meta.yaml
- recipe/scripts/activate.sh
- recipe/scripts/deactivate.sh
> [3.6.x] POSIX Compliant de/activate scripts

- recipe/meta.yaml
- recipe/scripts/deactivate.sh
> [3.6.x] Fix deactivate.sh

- recipe/meta.yaml
- recipe/scripts/deactivate.sh
> Fix deactivate.sh script

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libdeflate119.yaml
- .ci_support/migrations/libtiff46.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> rebuild for libtiff46, libdeflate 1.19

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libdeflate119.yaml
- .ci_support/migrations/libtiff46.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Checklist
Dependency issues necessitating migrating both at once.
> rebuild for libdeflate 1.19, libtiff 4.6

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/build_arrow_parquet.bat
- recipe/build_arrow_parquet.sh
- recipe/meta.yaml
Add extra commit to https://github.com/conda-forge/gdal-feedstock/pull/805
> Remove build: skip to enable later libarrow versions (cont'd)

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libjpeg_turbo3.yaml
- .ci_support/migrations/libtiff46.yaml
- .ci_support/migrations/poppler2402.yaml
- .ci_support/migrations/proj931.yaml
- .ci_support/migrations/tiledb218.yaml
- .ci_support/migrations/tiledb219.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- recipe/meta.yaml
Checklist
I think the bot has been falling behind on sending migrations to this branch.  Will see how far this gets, perhaps need to bunch some builds together.
> Poppler 24.02 [v3.7.x]

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/hdf51142.yaml
- .ci_support/migrations/tiledb220.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Checklist
* [c] Bumped the build number (if the version is unchanged)
I suppose I should figure out why the bot is not doing these automagically, but in the meantime...
> rebuild for tiledb 2.20 [v3.7.x branch]

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/geotiff173.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Use libkml-devel

- .azure-pipelines/azure-pipelines-win.yml
- conda-forge.yml
Checklist
@conda-forge-admin, please rerender 
Closes #993
> use drive_c

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/poppler2411.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Checklist
Jumping ahead of the bot as we need a manual code change anyway for #1012 and I am impatient.
> Rebuild for poppler 24.11

- recipe/meta.yaml
Checklist
refs #1016 
backports #1017 from main branch to `v3.9.x` branch
> pin plugins to exact libgdal-core build

- recipe/meta.yaml
- recipe/poppler_25_05_0_compat.patch
> [v3.10.x] Add compatibility with Poppler 25.05.00

- .ci_support/migrations/libdeflate124.yaml
- .ci_support/migrations/tiledb228.yaml
- recipe/meta.yaml
- recipe/setuptools_80_compat.patch
> Fix Python bindings builds on Windows with setuptools >= 80

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/proj96.yaml
- .ci_support/migrations/python314.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Same as #1110 but for the `main` branch.
Checklist
> Rebuild for python 3.14
